--- #YAML:1.0
name:                WebService-Viddler
version:             0.10
abstract:             An encapsulation of the Viddler video platform in Perl
license:             perl
author:              
    - Paul Weinstein <pdw@weinstein.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
